import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import jsdoc from "eslint-plugin-jsdoc";
import prettier from "eslint-config-prettier";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // dist: build output, never linted
  // src/components/ui: auto-generated by shadcn — do not modify or lint
  globalIgnores(["dist", "src/components/ui"]),

  // ── Base rules for all TypeScript/TSX files ───────────────────────────────
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      // Must be last — disables all ESLint rules that conflict with Prettier.
      prettier,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Allow unused parameters prefixed with _ (e.g. _env, _index).
      // This is a common TypeScript convention for intentionally ignored parameters.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
    },
  },

  // ── JSDoc rules: enforce complete documentation ───────────────────────────
  //
  // Applied only to .ts files in src/core/ (the math engine).
  // React components (.tsx) are excluded — JSDoc is less common there and
  // prop types are already documented via TypeScript interfaces.
  //
  // Note: @param and @returns type annotations (e.g. {string}) are NOT required
  // here because TypeScript already carries that information. Duplicating types
  // in JSDoc would only create drift when types change.
  {
    files: ["src/core/**/*.ts"],
    plugins: { jsdoc },
    settings: {
      // Tell eslint-plugin-jsdoc that we're working in a TypeScript project.
      jsdoc: { mode: "typescript" },
    },
    rules: {
      // Every exported class, method and function must have a JSDoc block.
      "jsdoc/require-jsdoc": [
        "warn",
        {
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true,
            ArrowFunctionExpression: false, // too noisy for short callbacks
            FunctionExpression: false,
          },
          checkConstructors: true,
        },
      ],

      // Every function parameter must be documented with @param.
      "jsdoc/require-param": "warn",

      // Every @param must have a description (not just the name).
      "jsdoc/require-param-description": "warn",

      // Do NOT require {type} annotations in @param — TypeScript already has them.
      "jsdoc/require-param-type": "off",

      // @param names must match actual parameter names.
      "jsdoc/check-param-names": "warn",

      // Functions that return a non-void value must have @returns.
      "jsdoc/require-returns": "warn",

      // @returns must include a description.
      "jsdoc/require-returns-description": "warn",

      // Do NOT require {type} in @returns — TypeScript already has it.
      "jsdoc/require-returns-type": "off",

      // Class properties should have a JSDoc block.
      "jsdoc/require-property": "warn",

      // Every @property must have a description.
      "jsdoc/require-property-description": "warn",

      // Warn on common JSDoc tag mistakes.
      "jsdoc/check-tag-names": "warn",
      "jsdoc/check-types": "warn",

      // Every class, method and function description must start with a capital letter.
      "jsdoc/require-description": [
        "warn",
        {
          contexts: ["ClassDeclaration", "MethodDefinition", "FunctionDeclaration"],
        },
      ],
    },
  },
]);
